name: ytv
description: Torrent Videos Downloader

publish_to: 'none' 
version: 2.2.1+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  flutter_screenutil: ^5.0.0+2
  device_preview: ^0.7.3
  http: ^0.13.3
  cached_network_image: ^3.0.0
  form_field_validator: ^1.1.0
  form_validator: ^0.1.7
  auto_size_text: ^3.0.0
  google_fonts: ^2.1.0
  provider: any
  video_player: ^2.2.3
  chewie: ^1.2.2
  flutter_downloader: ^1.7.1
  permission_handler: ^8.1.6
  collection: ^1.15.0
  flutter_typeahead: ^3.2.4
  hive: ^2.0.5
  hive_generator: ^1.1.1
  path_provider: ^2.0.4
  animated_text_kit: ^4.2.1
  open_file: ^3.2.1
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_in_app_messaging: ^0.6.0+5
  firebase_app_installations: ^0.1.0+4
  firebase_remote_config: ^1.0.3
  firebase_messaging: ^11.2.4
  flutter_fgbg: ^0.1.0
  google_mobile_ads: ^1.0.1
  restart_app: ^1.1.0
  filesystem_picker: ^2.0.0
  url_launcher: ^6.0.10
  flutter_flavor: ^3.0.3
  flutter_slider_drawer: ^2.0.0
  share_plus: ^3.0.1
  intent:
    git:
      url: git://github.com/sis1124/intent.git
      ref: master 
  

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

 
  fonts:
    - family: Tourner
      fonts:
        - asset: assets/fonts/Tourner.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

